# Generated by Django 2.1.7 on 2019-02-13 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CuratedContentBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
            ],
        ),
        migrations.CreateModel(
            name='CuratedContentInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_status', models.IntegerField(choices=[(-1, 'NEVER Available'), (0, 'USE "Live as of Date"'), (1, 'ALWAYS Available')], default=0, verbose_name='Publish Status')),
                ('live_as_of', models.DateTimeField(blank=True, help_text='You can Set this to a future date/time to schedule availability.', null=True, verbose_name='Live As Of')),
                ('default_live', models.BooleanField(default=False, help_text='If everything else fails, then return this as the live home page', verbose_name='Default as Live')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Content')),
                ('content_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='curcon.CuratedContentBlock')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
