# Generated by Django 2.1.7 on 2019-02-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curcon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curatedcontentinstance',
            name='instance_title',
            field=models.CharField(default='default', help_text='Use this to describe what is different about this instance from the others, e.g., "when service is offline"', max_length=200, verbose_name='Instance Title'),
            preserve_default=False,
        ),
    ]
